import { Channel } from "./channel.ts";

export const ChannelLayoutMap = {
  "mono": [Channel.frontCenter],
  "stereo": [Channel.frontLeft, Channel.frontRight],
  "2.1": [Channel.frontLeft, Channel.frontRight, Channel.lowFrequency],
  "3.0": [Channel.frontLeft, Channel.frontRight, Channel.frontCenter],
  "3.0(back)": [Channel.frontLeft, Channel.frontRight, Channel.backCenter],
  "4.0": [
    Channel.frontLeft,
    Channel.frontRight,
    Channel.frontCenter,
    Channel.backCenter,
  ],
  "quad": [
    Channel.frontLeft,
    Channel.frontRight,
    Channel.backLeft,
    Channel.backRight,
  ],
  "quad(side)": [
    Channel.frontLeft,
    Channel.frontRight,
    Channel.sideLeft,
    Channel.sideRight,
  ],
  "3.1": [
    Channel.frontLeft,
    Channel.frontRight,
    Channel.frontCenter,
    Channel.lowFrequency,
  ],
  "5.0": [
    Channel.frontLeft,
    Channel.frontRight,
    Channel.frontCenter,
    Channel.backLeft,
    Channel.backRight,
  ],
  "5.0(side)": [
    Channel.frontLeft,
    Channel.frontRight,
    Channel.frontCenter,
    Channel.sideLeft,
    Channel.sideRight,
  ],
  "4.1": [
    Channel.frontLeft,
    Channel.frontRight,
    Channel.frontCenter,
    Channel.lowFrequency,
    Channel.backCenter,
  ],
  "5.1": [
    Channel.frontLeft,
    Channel.frontRight,
    Channel.frontCenter,
    Channel.lowFrequency,
    Channel.backLeft,
    Channel.backRight,
  ],
  "5.1(side)": [
    Channel.frontLeft,
    Channel.frontRight,
    Channel.frontCenter,
    Channel.lowFrequency,
    Channel.sideLeft,
    Channel.sideRight,
  ],
  "6.0": [
    Channel.frontLeft,
    Channel.frontRight,
    Channel.frontCenter,
    Channel.backCenter,
    Channel.sideLeft,
    Channel.sideRight,
  ],
  "6.0(front)": [
    Channel.frontLeft,
    Channel.frontRight,
    Channel.frontLeftOfCenter,
    Channel.frontRightOfCenter,
    Channel.sideLeft,
    Channel.sideRight,
  ],
  "hexagonal": [
    Channel.frontLeft,
    Channel.frontRight,
    Channel.frontCenter,
    Channel.backLeft,
    Channel.backRight,
    Channel.backCenter,
  ],
  "6.1": [
    Channel.frontLeft,
    Channel.frontRight,
    Channel.frontCenter,
    Channel.lowFrequency,
    Channel.backCenter,
    Channel.sideLeft,
    Channel.sideRight,
  ],
  "6.1(back)": [
    Channel.frontLeft,
    Channel.frontRight,
    Channel.frontCenter,
    Channel.lowFrequency,
    Channel.backLeft,
    Channel.backRight,
    Channel.backCenter,
  ],
  "6.1(front)": [
    Channel.frontLeft,
    Channel.frontRight,
    Channel.lowFrequency,
    Channel.frontLeftOfCenter,
    Channel.frontRightOfCenter,
    Channel.sideLeft,
    Channel.sideRight,
  ],
  "7.0": [
    Channel.frontLeft,
    Channel.frontRight,
    Channel.frontCenter,
    Channel.backLeft,
    Channel.backRight,
    Channel.sideLeft,
    Channel.sideRight,
  ],
  "7.0(front)": [
    Channel.frontLeft,
    Channel.frontRight,
    Channel.frontCenter,
    Channel.frontLeftOfCenter,
    Channel.frontRightOfCenter,
    Channel.sideLeft,
    Channel.sideRight,
  ],
  "7.1": [
    Channel.frontLeft,
    Channel.frontRight,
    Channel.frontCenter,
    Channel.lowFrequency,
    Channel.backLeft,
    Channel.backRight,
    Channel.sideLeft,
    Channel.sideRight,
  ],
  "7.1(wide)": [
    Channel.frontLeft,
    Channel.frontRight,
    Channel.frontCenter,
    Channel.lowFrequency,
    Channel.backLeft,
    Channel.backRight,
    Channel.frontLeftOfCenter,
    Channel.frontRightOfCenter,
  ],
  "7.1(wide-side)": [
    Channel.frontLeft,
    Channel.frontRight,
    Channel.frontCenter,
    Channel.lowFrequency,
    Channel.frontLeftOfCenter,
    Channel.frontRightOfCenter,
    Channel.sideLeft,
    Channel.sideRight,
  ],
  "octagonal": [
    Channel.frontLeft,
    Channel.frontRight,
    Channel.frontCenter,
    Channel.backLeft,
    Channel.backRight,
    Channel.backCenter,
    Channel.sideLeft,
    Channel.sideRight,
  ],
  "hexadecagonal": [
    Channel.frontLeft,
    Channel.frontRight,
    Channel.frontCenter,
    Channel.backLeft,
    Channel.backRight,
    Channel.backCenter,
    Channel.sideLeft,
    Channel.sideRight,
    Channel.topFrontLeft,
    Channel.topFrontCenter,
    Channel.topFrontRight,
    Channel.topBackLeft,
    Channel.topBackCenter,
    Channel.topBackRight,
    Channel.wideLeft,
    Channel.wideRight,
  ],
  "downmix": [Channel.downmixLeft, Channel.downmixRight],
  "22.2": [
    Channel.frontLeft,
    Channel.frontRight,
    Channel.frontCenter,
    Channel.lowFrequency,
    Channel.backLeft,
    Channel.backRight,
    Channel.topFrontLeft,
    Channel.topFrontRight,
    Channel.backCenter,
    Channel.sideLeft,
    Channel.sideRight,
    Channel.topCenter,
    Channel.topFrontLeft,
    Channel.topFrontCenter,
    Channel.topFrontRight,
    Channel.topBackLeft,
    Channel.topBackCenter,
    Channel.topBackRight,
    Channel.lowFrequency2,
    Channel.topSideLeft,
    Channel.topSideRight,
    Channel.topBackLeft,
    Channel.topBackCenter,
    Channel.topBackRight,
  ],
};
